// SPDX-License-Identifier: AGPL-3.0-or-later

export const DEPLOYED_OFFICIAL_DOCUMENT = {
	api_code_version: 1,
	endpoints: {
		api: 'https://api.fluxer.app',
		api_client: 'https://api.fluxer.app',
		api_public: 'https://api.fluxer.app',
		gateway: 'wss://gateway.fluxer.app',
		media: 'https://media.fluxer.app',
		static_cdn: 'https://cdn.fluxer.app',
		marketing: 'https://fluxer.app',
		admin: 'https://admin.fluxer.app',
		invite: 'https://fluxer.gg',
		gift: 'https://fluxer.gift',
		webapp: 'https://web.fluxer.app',
	},
	captcha: {provider: 'altcha'},
	features: {
		voice_enabled: true,
		stripe_enabled: true,
		self_hosted: false,
		presigned_attachment_uploads: true,
		emails_enabled: true,
	},
	gif: {provider: 'klipy', display_name: 'Klipy', attribution_required: false},
	sso: {enabled: false, enforced: false, display_name: null, redirect_uri: 'https://web.fluxer.app/sso/callback'},
	registration: {mode: 'open', admin_registration_urls_enabled: true},
	community: {single_community: false, single_community_guild_id: null, direct_messages_disabled: false},
	services: {gif_enabled: true, youtube_enabled: true, bluesky_enabled: false},
	limits: {
		version: 2,
		traitDefinitions: ['premium'],
		rules: [
			{id: 'default', overrides: {max_guild_emojis: 50}},
			{id: 'premium', filters: {traits: ['premium'], guildFeatures: []}, overrides: {max_guild_emojis: 250}},
		],
		defaultsHash: 'deployed-defaults-hash',
	},
	push: {public_vapid_key: 'BPublicVapidKey'},
	app_public: {
		branding: {
			product_name: 'Fluxer',
			icon_url: 'https://cdn.fluxer.app/icon.png',
			symbol_url: 'https://cdn.fluxer.app/symbol.png',
			logo_url: 'https://cdn.fluxer.app/logo.png',
			wordmark_url: 'https://cdn.fluxer.app/wordmark.png',
			favicon_url: 'https://cdn.fluxer.app/favicon.png',
			theme_color: '#5865f2',
		},
		setup: {configured: true, admin_url: 'https://admin.fluxer.app'},
		legal: {terms_url: 'https://fluxer.app/terms', privacy_url: 'https://fluxer.app/privacy'},
		registration: {collect_date_of_birth: true},
	},
} as const;

export const SELF_HOSTED_API_TOPOLOGY_DOCUMENT = {
	api_code_version: 1,
	endpoints: {
		api: 'https://chat.example.test/api',
		api_client: 'https://chat.example.test/api',
		api_public: 'https://chat.example.test/api',
		gateway: 'wss://chat.example.test/gateway',
		media: 'https://chat.example.test/media',
		static_cdn: 'https://chat.example.test',
		marketing: 'https://chat.example.test/marketing',
		admin: 'https://chat.example.test/admin',
		invite: 'https://chat.example.test/invite',
		gift: 'https://chat.example.test/gift',
		webapp: 'https://chat.example.test',
	},
	captcha: {provider: 'none'},
	features: {
		voice_enabled: false,
		stripe_enabled: false,
		self_hosted: true,
		presigned_attachment_uploads: false,
		emails_enabled: false,
	},
	gif: {provider: 'klipy', display_name: 'Klipy', attribution_required: false},
	sso: {enabled: false, enforced: false, display_name: null, redirect_uri: 'https://chat.example.test/sso/callback'},
	registration: {mode: 'closed', admin_registration_urls_enabled: false},
	community: {single_community: true, single_community_guild_id: '1', direct_messages_disabled: false},
	services: {gif_enabled: false, youtube_enabled: false, bluesky_enabled: false},
	limits: {version: 1, traitDefinitions: [], rules: []},
	push: {public_vapid_key: null},
	app_public: {
		branding: {
			product_name: 'Example Chat',
			icon_url: null,
			symbol_url: null,
			logo_url: null,
			wordmark_url: null,
			favicon_url: null,
			theme_color: null,
		},
		setup: {configured: true, admin_url: 'https://chat.example.test/admin'},
		legal: {terms_url: null, privacy_url: null},
		registration: {collect_date_of_birth: false},
	},
} as const;

export const UPGRADED_DOCUMENT = {
	codename: 'tungsten',
	api_code_version: 1,
	endpoints: {
		...DEPLOYED_OFFICIAL_DOCUMENT.endpoints,
		upload_relay: 'https://media.fluxer.app/upload',
		docs: 'https://fluxer.app/docs',
	},
	captcha: DEPLOYED_OFFICIAL_DOCUMENT.captcha,
	features: {...DEPLOYED_OFFICIAL_DOCUMENT.features, account_deletion_grace_period_hours: 720},
	gif: DEPLOYED_OFFICIAL_DOCUMENT.gif,
	sso: {...DEPLOYED_OFFICIAL_DOCUMENT.sso, available: true},
	registration: DEPLOYED_OFFICIAL_DOCUMENT.registration,
	community: DEPLOYED_OFFICIAL_DOCUMENT.community,
	services: DEPLOYED_OFFICIAL_DOCUMENT.services,
	limits: DEPLOYED_OFFICIAL_DOCUMENT.limits,
	push: {
		public_vapid_key: 'BPublicVapidKey',
		delivery_mode: 'direct',
		event_resolution_path: '/v1/push/events/{event_id}',
		external_relay_url: null,
		relay_signing_key_hashes: null,
	},
	app_public: DEPLOYED_OFFICIAL_DOCUMENT.app_public,
	age_policy: {
		geos: [
			{country_code: 'GB', region_code: null, action: 'restrict', card_verification_available: false},
			{country_code: 'US', region_code: 'MS', action: 'block', card_verification_available: false},
		],
	},
} as const;
